export const orderMessage = [
  {
    key: 'A',
    msg: '请登录后再试',
    type: 'error'
  }, {
    key: 'F',
    msg: '订单有效时间异常，请稍后重试',
    type: 'error'
  }, {
    key: 'S',
    msg: '您输入的价格有误，请检查后重试',
    type: 'error'
  }, {
    key: 'P',
    msg: '你操作的产品已下架，如有疑问请联系客服',
    type: 'error'
  }, {
    key: 'C',
    msg: '您输入的价格有误，请检查后重试',
    type: 'error'
  }, {
    key: 'Y',
    msg: '操作异常，请稍后重试',
    type: 'error'
  }, {
    key: 'X',
    msg: '您的账号异常，请及时联系客服',
    type: 'error'
  }, {
    key: 'T',
    msg: '您操作的订单类型不支持，请检查后重试',
    type: 'error'
  }, {
    key: 'M',
    msg: '你操作的产品不支持，如有疑问请联系客服',
    type: 'error'
  }, {
    key: 'N',
    msg: '您输入的价格有误，请检查后重试',
    type: 'error'
  }, {
    key: 'Q',
    msg: '您输入的数量有误，请检查后重试',
    type: 'error'
  }, {
    key: 'J',
    msg: '您的账号已被锁住，如有疑问请联系客服',
    type: 'error'
  }, {
    key: 'U',
    msg: '您的资金不足，请充值后重试',
    type: 'error'
  }, {
    key: 'V',
    msg: '该用户不存在，如有疑问请联系客服',
    type: 'error'
  }, {
    key: 'W',
    msg: '您交易过于频繁，请稍后交易',
    type: 'error'
  }, {
    key: 'R',
    msg: '订单取消成功',
    type: 'success'
  },
  {
    key: '1',
    msg: '部分成交',
    type: 'success'
  }, {
    key: '2',
    msg: '提交成功',
    type: 'success'
  }, {
    key: '3',
    msg: '订单已取消',
    type: 'success'
  }, {
    key: '4',
    msg: 'CANCELED',
    type: 'error'
  }, {
    key: '5',
    msg: 'REPLACED',
    type: 'error'
  }, {
    key: '6',
    msg: 'PENDING_CANCEL',
    type: 'error'
  }, {
    key: '7',
    msg: '订单取消失败',
    type: 'error'
  }, {
    key: '8',
    msg: '您操作的订单类型不支持，请检查后重试',
    type: 'error'
  }, {
    key: '9',
    msg: 'SUSPENDED',
    type: 'error'
  }, {
    key: 'B',
    msg: 'CALCULATED',
    type: 'error'
  }, {
    key: 'D',
    msg: 'ACCEPTED_FOR_BIDDING',
    type: 'error'
  }, {
    key: 'E',
    msg: 'PENDING_REPLACE',
    type: 'error'
  }, {
    key: 'Z',
    msg: '止损或者止盈价格设置错误，请检查！',
    type: 'error'
  }

]
